/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    propuestas: Propuesta;
    noticias: Noticia;
    entrevistas: Entrevista;
    contactos: Contacto;
    sugerencias: Sugerencia;
    'testigos-electorales': TestigosElectorale;
    reuniones: Reunione;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    propuestas: PropuestasSelect<false> | PropuestasSelect<true>;
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    entrevistas: EntrevistasSelect<false> | EntrevistasSelect<true>;
    contactos: ContactosSelect<false> | ContactosSelect<true>;
    sugerencias: SugerenciasSelect<false> | SugerenciasSelect<true>;
    'testigos-electorales': TestigosElectoralesSelect<false> | TestigosElectoralesSelect<true>;
    reuniones: ReunionesSelect<false> | ReunionesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'hoja-de-vida': HojaDeVida;
    'ajustes-sitio': AjustesSitio;
    'estadisticas': Estadisticas;
  };
  globalsSelect: {
    'hoja-de-vida': HojaDeVidaSelect<false> | HojaDeVidaSelect<true>;
    'ajustes-sitio': AjustesSitioSelect<false> | AjustesSitioSelect<true>;
    'estadisticas': EstadisticasSelect<false> | EstadisticasSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "propuestas".
 */
export interface Propuesta {
  id: number;
  titulo: string;
  /**
   * Se genera automáticamente desde el título si se deja vacío.
   */
  slug?: string | null;
  eje: 'educacion' | 'seguridad' | 'salud' | 'empleo' | 'movilidad' | 'ambiente' | 'cultura' | 'gobierno' | 'otro';
  /**
   * Las propuestas se muestran de menor a mayor número.
   */
  orden?: number | null;
  /**
   * Ej.: 📚, 🚓, 🌳
   */
  icono?: string | null;
  /**
   * Una o dos frases que se muestran en el listado.
   */
  resumen: string;
  imagen?: (number | null) | Media;
  contenido?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe la imagen (accesibilidad y SEO).
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: number;
  titulo: string;
  /**
   * Se genera automáticamente desde el título si se deja vacío.
   */
  slug?: string | null;
  fecha: string;
  portada?: (number | null) | Media;
  /**
   * Texto breve que aparece en el listado y al compartir.
   */
  resumen: string;
  contenido: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entrevistas".
 */
export interface Entrevista {
  id: number;
  titulo: string;
  /**
   * Se genera automáticamente desde el título si se deja vacío.
   */
  slug?: string | null;
  /**
   * "Realizada" muestra el video; "Próxima" se muestra en la agenda.
   */
  estado: 'realizada' | 'proxima';
  /**
   * Ej.: Caracol Radio, Noticias RCN, Canal local...
   */
  medio: string;
  fecha: string;
  /**
   * Red social donde está publicada la entrevista.
   */
  plataforma?: ('youtube' | 'facebook' | 'tiktok' | 'instagram') | null;
  /**
   * Pega el enlace de la entrevista. YouTube y TikTok se incrustan; Facebook muestra el reproductor; Instagram muestra un enlace.
   */
  urlVideo?: string | null;
  /**
   * Para entrevistas próximas: dónde se podrá ver en vivo.
   */
  enlaceTransmision?: string | null;
  descripcion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactos".
 */
export interface Contacto {
  id: number;
  nombre: string;
  email: string;
  telefono?: string | null;
  esVoluntario?: boolean | null;
  mensaje?: string | null;
  atendido?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sugerencias".
 */
export interface Sugerencia {
  id: number;
  sugerencia: string;
  nombre?: string | null;
  email?: string | null;
  telefono?: string | null;
  atendido?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testigos-electorales".
 */
export interface TestigosElectorale {
  id: number;
  nombreCompleto: string;
  tipoDocumento: 'CC' | 'CE' | 'TI' | 'PA';
  numeroDocumento: string;
  celular: string;
  puestoVotacion:
    | 'casd-barrio-san-antonio'
    | 'carcel'
    | 'col-boyaca-jose-ignacio-marquez'
    | 'col-boyaca-fco-paula-santander'
    | 'colegio-salesiano-maldonado'
    | 'coliseo-cubierto-municipal'
    | 'coliseo-irdet'
    | 'coliseo-municipal-comfaboy'
    | 'coliseo-san-antonio'
    | 'coliseo-uniboyaca'
    | 'crib'
    | 'ie-gustavo-rojas-pinilla-central'
    | 'ie-antonio-jose-sandoval-gomez'
    | 'ie-libertador-simon-bolivar-central'
    | 'puente-de-boyaca'
    | 'puesto-censo-san-agustin'
    | 'universidad-santo-tomas'
    | 'auditorio-gustavo-castellanos-comfaboy'
    | 'ie-silvino-rodriguez-manzanares'
    | 'it-gonzalo-suarez-rendon-central'
    | 'ie-libertador-simon-bolivar-san-francisco'
    | 'ie-normal-superior-jardin-nacional'
    | 'ies-juan-castellanos-crisanto-luque'
    | 'inem-carlos-arturo-torres-central'
    | 'ns-leonor-alvarez-pinzon-primaria'
    | 'universidad-juan-de-castellanos';
  contactado?: ('si' | 'no') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reuniones".
 */
export interface Reunione {
  id: number;
  nombre: string;
  lugar: string;
  fechaHora: string;
  estado?: ('solicitada' | 'confirmada' | 'rechazada') | null;
  nota?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nombre?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'propuestas';
        value: number | Propuesta;
      } | null)
    | ({
        relationTo: 'noticias';
        value: number | Noticia;
      } | null)
    | ({
        relationTo: 'entrevistas';
        value: number | Entrevista;
      } | null)
    | ({
        relationTo: 'contactos';
        value: number | Contacto;
      } | null)
    | ({
        relationTo: 'sugerencias';
        value: number | Sugerencia;
      } | null)
    | ({
        relationTo: 'testigos-electorales';
        value: number | TestigosElectorale;
      } | null)
    | ({
        relationTo: 'reuniones';
        value: number | Reunione;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "propuestas_select".
 */
export interface PropuestasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  eje?: T;
  orden?: T;
  icono?: T;
  resumen?: T;
  imagen?: T;
  contenido?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  fecha?: T;
  portada?: T;
  resumen?: T;
  contenido?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entrevistas_select".
 */
export interface EntrevistasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  estado?: T;
  medio?: T;
  fecha?: T;
  plataforma?: T;
  urlVideo?: T;
  enlaceTransmision?: T;
  descripcion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactos_select".
 */
export interface ContactosSelect<T extends boolean = true> {
  nombre?: T;
  email?: T;
  telefono?: T;
  esVoluntario?: T;
  mensaje?: T;
  atendido?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sugerencias_select".
 */
export interface SugerenciasSelect<T extends boolean = true> {
  sugerencia?: T;
  nombre?: T;
  email?: T;
  telefono?: T;
  atendido?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testigos-electorales_select".
 */
export interface TestigosElectoralesSelect<T extends boolean = true> {
  nombreCompleto?: T;
  tipoDocumento?: T;
  numeroDocumento?: T;
  celular?: T;
  puestoVotacion?: T;
  contactado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reuniones_select".
 */
export interface ReunionesSelect<T extends boolean = true> {
  nombre?: T;
  lugar?: T;
  fechaHora?: T;
  estado?: T;
  nota?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nombre?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hoja-de-vida".
 */
export interface HojaDeVida {
  id: number;
  nombreCompleto: string;
  cargoAspirado?: string | null;
  foto?: (number | null) | Media;
  biografia?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  formacion?:
    | {
        titulo: string;
        institucion?: string | null;
        anio?: string | null;
        id?: string | null;
      }[]
    | null;
  experiencia?:
    | {
        cargo: string;
        organizacion?: string | null;
        periodo?: string | null;
        descripcion?: string | null;
        id?: string | null;
      }[]
    | null;
  logros?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ajustes-sitio".
 */
export interface AjustesSitio {
  id: number;
  nombreSitio: string;
  lema?: string | null;
  logo?: (number | null) | Media;
  redes?: {
    facebook?: string | null;
    instagram?: string | null;
    x?: string | null;
    tiktok?: string | null;
  };
  contacto?: {
    email?: string | null;
    telefono?: string | null;
    direccion?: string | null;
  };
  /**
   * Ej.: Comité de campaña — Tunja 2027
   */
  textoPie?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hoja-de-vida_select".
 */
export interface HojaDeVidaSelect<T extends boolean = true> {
  nombreCompleto?: T;
  cargoAspirado?: T;
  foto?: T;
  biografia?: T;
  formacion?:
    | T
    | {
        titulo?: T;
        institucion?: T;
        anio?: T;
        id?: T;
      };
  experiencia?:
    | T
    | {
        cargo?: T;
        organizacion?: T;
        periodo?: T;
        descripcion?: T;
        id?: T;
      };
  logros?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estadisticas".
 */
export interface Estadisticas {
  id: number;
  totalVisitas?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estadisticas_select".
 */
export interface EstadisticasSelect<T extends boolean = true> {
  totalVisitas?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ajustes-sitio_select".
 */
export interface AjustesSitioSelect<T extends boolean = true> {
  nombreSitio?: T;
  lema?: T;
  logo?: T;
  redes?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        x?: T;
        tiktok?: T;
      };
  contacto?:
    | T
    | {
        email?: T;
        telefono?: T;
        direccion?: T;
      };
  textoPie?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}